nodes:
  unet_loader:
    class_type: UNETLoader
    title: "Load Diffusion Model"
    params:
      weight_dtype: "default"
  clip_loader:
    class_type: DualCLIPLoader
    title: "Load Dual CLIP"
    params:
      clip_name1: "qwen_2.5_vl_7b_fp8_scaled.safetensors"
      clip_name2: "clip_l.safetensors"
      type: "kandinsky5"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "hunyuan_video_vae_bf16.safetensors"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative Prompt)"
  kandinsky_preprocessor:
    class_type: Kandinsky5ImageToVideo
    title: "Kandinsky5 Preprocessor"
    params:
      batch_size: 1
  model_sampler:
    class_type: ModelSamplingSD3
    title: "Model Sampler"
    params:
      shift: 5.0
  ksampler:
    class_type: KSampler
    title: "KSampler"
    params:
      steps: 50
      cfg: 5.0
      sampler_name: "euler_ancestral"
      scheduler: "beta"
      denoise: 1.0
  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
  create_video:
    class_type: CreateVideo
    title: "Create Video"
    params:
      fps: 24
  save_video:
    class_type: SaveVideo
    title: "Save Video"
    params:
      format: "mp4"
      codec: "h264"

connections:
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "pos_prompt:0"
    to: "kandinsky_preprocessor:positive"
  - from: "neg_prompt:0"
    to: "kandinsky_preprocessor:negative"
  - from: "vae_loader:0"
    to: "kandinsky_preprocessor:vae"
    
  - from: "unet_loader:0"
    to: "model_sampler:model"
  - from: "model_sampler:0"
    to: "ksampler:model"
    
  - from: "kandinsky_preprocessor:0"
    to: "ksampler:positive"
  - from: "kandinsky_preprocessor:1"
    to: "ksampler:negative"
  - from: "kandinsky_preprocessor:2"
    to: "ksampler:latent_image"

  - from: "ksampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"

ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  width: "kandinsky_preprocessor:width"
  height: "kandinsky_preprocessor:height"
  seed: "ksampler:seed"
  filename_prefix: "save_video:filename_prefix"
  unet_name: "unet_loader:unet_name"
  video_length: "kandinsky_preprocessor:length"