nodes:
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      type: "wan"
      device: "default"
      clip_name: "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "wan_2.1_vae.safetensors"
  unet_loader_high:
    class_type: UNETLoader
    title: "Load UNET High Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_i2v_A14b_high_noise_scaled_fp8_e4m3_lightx2v_4step_comfyui_1030.safetensors"
  unet_loader_low:
    class_type: UNETLoader
    title: "Load UNET Low Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_i2v_A14b_low_noise_scaled_fp8_e4m3_lightx2v_4step_comfyui.safetensors"
  start_image_loader:
    class_type: LoadImage
    title: "Load Start Image"
  end_image_loader:
    class_type: LoadImage
    title: "Load End Image"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative Prompt)"
  flfv_preprocessor:
    class_type: WanFirstLastFrameToVideo
    title: "WanFirstLastFrameToVideo"
    params:
      batch_size: 1
  model_sampler_high:
    class_type: ModelSamplingSD3
    params: { shift: 5.0 }
  model_sampler_low:
    class_type: ModelSamplingSD3
    params: { shift: 5.0 }
  ksampler_high:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) High Noise"
    params:
      add_noise: "enable"
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 0
      end_at_step: 2
      return_with_leftover_noise: "enable"
  ksampler_low:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) Low Noise"
    params:
      add_noise: "disable"
      noise_seed: 0
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 2
      end_at_step: 4
      return_with_leftover_noise: "disable"
  vae_decode:
    class_type: VAEDecode
  create_video:
    class_type: CreateVideo
    params: { fps: 16 }
  save_video:
    class_type: SaveVideo
    params:
      format: "mp4"
      codec: "h264"
connections:
  - from: "unet_loader_high:0"
    to: "model_sampler_high:model"
  - from: "unet_loader_low:0"
    to: "model_sampler_low:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "pos_prompt:0"
    to: "flfv_preprocessor:positive"
  - from: "neg_prompt:0"
    to: "flfv_preprocessor:negative"
  - from: "vae_loader:0"
    to: "flfv_preprocessor:vae"
  - from: "start_image_loader:0"
    to: "flfv_preprocessor:start_image"
  - from: "end_image_loader:0"
    to: "flfv_preprocessor:end_image"
  - from: "model_sampler_high:0"
    to: "ksampler_high:model"
  - from: "flfv_preprocessor:0"
    to: "ksampler_high:positive"
  - from: "flfv_preprocessor:1"
    to: "ksampler_high:negative"
  - from: "flfv_preprocessor:2"
    to: "ksampler_high:latent_image"
  - from: "ksampler_high:0"
    to: "ksampler_low:latent_image"
  - from: "model_sampler_low:0"
    to: "ksampler_low:model"
  - from: "flfv_preprocessor:0"
    to: "ksampler_low:positive"
  - from: "flfv_preprocessor:1"
    to: "ksampler_low:negative"
  - from: "ksampler_low:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"
ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  start_image: "start_image_loader:image"
  end_image: "end_image_loader:image"
  aspect_ratio:
    width: "flfv_preprocessor:width"
    height: "flfv_preprocessor:height"
  video_length: "flfv_preprocessor:length"
  seed: "ksampler_high:noise_seed"
  filename_prefix: "save_video:filename_prefix"

dynamic_easycache_chains:
  use_easy_cache:
    ksampler_node:
      - "ksampler_high"
      - "ksampler_low"