nodes:
  unet_loader:
    class_type: UnetLoaderGGUF
    title: "Unet Loader (GGUF)"
    params:
      unet_name: "flux2-dev-Q3_K_S.gguf"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "flux2-vae.safetensors"
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      clip_name: "mistral_3_small_flux2_fp8.safetensors"
      type: "flux2"
      device: "default"
  
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  
  flux_guidance:
    class_type: FluxGuidance
    title: "FluxGuidance"
    params:
      guidance: 4.0
    
  latent_source:
    class_type: EmptyFlux2LatentImage
    title: "Empty Flux 2 Latent"
    params:
      batch_size: 1
    
  scheduler:
    class_type: Flux2Scheduler
    title: "Flux2Scheduler"
    params:
      steps: 20

  noise_generator:
    class_type: RandomNoise
    title: "RandomNoise"

  guider:
    class_type: BasicGuider
    title: "BasicGuider"

  sampler_selector:
    class_type: KSamplerSelect
    title: "KSamplerSelect"
    params:
      sampler_name: "euler"

  sampler:
    class_type: SamplerCustomAdvanced
    title: "SamplerCustomAdvanced"

  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
    
  save_image:
    class_type: SaveImage
    title: "Save Image"

connections:
  - from: "unet_loader:0"
    to: "guider:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "pos_prompt:0"
    to: "flux_guidance:conditioning"
  - from: "flux_guidance:0"
    to: "guider:conditioning"
  - from: "guider:0"
    to: "sampler:guider"
  - from: "latent_source:0"
    to: "sampler:latent_image"
  - from: "scheduler:0"
    to: "sampler:sigmas"
  - from: "noise_generator:0"
    to: "sampler:noise"
  - from: "sampler_selector:0"
    to: "sampler:sampler"
  - from: "sampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "save_image:images"

dynamic_flux2_reference_chains:
  reference_chain:
    vae_node: "vae_loader"
    guider_node: "guider"

ui_map:
  positive_prompt: "pos_prompt:text"
  width: 
    - "latent_source:width"
    - "scheduler:width"
  height: 
    - "latent_source:height"
    - "scheduler:height"
  seed: "noise_generator:noise_seed"
  filename_prefix: "save_image:filename_prefix"