nodes:
  i2v_unet:
    class_type: UNETLoader
    title: "Load 480p Diffusion Model"
    params:
      unet_name: "hunyuanvideo1.5_480p_i2v_step_distilled_fp8_scaled.safetensors"
      weight_dtype: "default"
  clip_loader:
    class_type: DualCLIPLoader
    title: "Load Dual CLIP"
    params:
      clip_name1: "qwen_2.5_vl_7b_fp8_scaled.safetensors"
      clip_name2: "byt5_small_glyphxl_fp16.safetensors"
      type: "hunyuan_video_15"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "hunyuanvideo15_vae_fp16.safetensors"
  clip_vision_loader:
    class_type: CLIPVisionLoader
    title: "Load CLIP Vision"
    params:
      clip_name: "sigclip_vision_patch14_384.safetensors"
  load_image:
    class_type: LoadImage
    title: "Load Start Image"
  clip_vision_encode:
    class_type: CLIPVisionEncode
    title: "Encode Image with CLIP Vision"
    params:
      crop: "center"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative)"
  i2v_preprocessor:
    class_type: HunyuanVideo15ImageToVideo
    title: "I2V Preprocessor"
    params:
      batch_size: 1
  i2v_model_sampler:
    class_type: ModelSamplingSD3
    title: "Model Sampler (480p)"
    params:
      shift: 7.0
  i2v_scheduler:
    class_type: BasicScheduler
    title: "Scheduler (480p)"
    params:
      scheduler: "simple"
      steps: 8
      denoise: 1.0
  i2v_noise:
    class_type: RandomNoise
    title: "Random Noise (480p)"
  i2v_sampler_select:
    class_type: KSamplerSelect
    title: "Sampler Select (480p)"
    params:
      sampler_name: "euler"
  i2v_guider:
    class_type: CFGGuider
    title: "CFG Guider (480p)"
    params:
      cfg: 1.0
  i2v_sampler:
    class_type: SamplerCustomAdvanced
    title: "Advanced Sampler (480p)"
  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
  create_video:
    class_type: CreateVideo
    title: "Create Video"
    params:
      fps: 24
  save_video:
    class_type: SaveVideo
    title: "Save Video"
    params:
      format: "auto"
      codec: "h264"

connections:
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "clip_vision_loader:0"
    to: "clip_vision_encode:clip_vision"
  - from: "load_image:0"
    to: "clip_vision_encode:image"
  - from: "pos_prompt:0"
    to: "i2v_preprocessor:positive"
  - from: "neg_prompt:0"
    to: "i2v_preprocessor:negative"
  - from: "vae_loader:0"
    to: "i2v_preprocessor:vae"
  - from: "load_image:0"
    to: "i2v_preprocessor:start_image"
  - from: "clip_vision_encode:0"
    to: "i2v_preprocessor:clip_vision_output"
  - from: "i2v_unet:0"
    to: "i2v_model_sampler:model"
  - from: "i2v_unet:0"
    to: "i2v_scheduler:model"
  - from: "i2v_model_sampler:0"
    to: "i2v_guider:model"
  - from: "i2v_preprocessor:0"
    to: "i2v_guider:positive"
  - from: "i2v_preprocessor:1"
    to: "i2v_guider:negative"
  - from: "i2v_noise:0"
    to: "i2v_sampler:noise"
  - from: "i2v_guider:0"
    to: "i2v_sampler:guider"
  - from: "i2v_sampler_select:0"
    to: "i2v_sampler:sampler"
  - from: "i2v_scheduler:0"
    to: "i2v_sampler:sigmas"
  - from: "i2v_preprocessor:2"
    to: "i2v_sampler:latent_image"
  - from: "i2v_sampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"

ui_map:
  start_image: "load_image:image"
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  width: "i2v_preprocessor:width"
  height: "i2v_preprocessor:height"
  video_length: "i2v_preprocessor:length"
  seed: "i2v_noise:noise_seed"
  filename_prefix: "save_video:filename_prefix"