nodes:
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      type: "wan"
      device: "default"
      clip_name: "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "wan_2.1_vae.safetensors"
  unet_loader_high:
    class_type: UNETLoader
    title: "Load UNET High Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_fun_camera_high_noise_14B_fp8_scaled.safetensors"
  unet_loader_low:
    class_type: UNETLoader
    title: "Load UNET Low Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_fun_camera_low_noise_14B_fp8_scaled.safetensors"
  lora_loader_high:
    class_type: LoraLoaderModelOnly
    title: "Load LoRA High Noise"
    params:
      strength_model: 1.0
      lora_name: "wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors"
  lora_loader_low:
    class_type: LoraLoaderModelOnly
    title: "Load LoRA Low Noise"
    params:
      strength_model: 1.0
      lora_name: "wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors"
  start_image_loader:
    class_type: LoadImage
    title: "Load Start Image"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative Prompt)"
  camera_embed:
    class_type: WanCameraEmbedding
    title: "WanCameraEmbedding"
  camera_preprocessor:
    class_type: WanCameraImageToVideo
    title: "WanCameraImageToVideo"
    params:
      batch_size: 1
  model_sampler_high:
    class_type: ModelSamplingSD3
    params: { shift: 8.0 }
  model_sampler_low:
    class_type: ModelSamplingSD3
    params: { shift: 8.0 }
  ksampler_high:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) High Noise"
    params:
      add_noise: "enable"
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 0
      end_at_step: 2
      return_with_leftover_noise: "enable"
  ksampler_low:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) Low Noise"
    params:
      add_noise: "disable"
      noise_seed: 0
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 2
      end_at_step: 4
      return_with_leftover_noise: "disable"
  vae_decode:
    class_type: VAEDecode
  create_video:
    class_type: CreateVideo
    params: { fps: 16 }
  save_video:
    class_type: SaveVideo
    params:
      format: "mp4"
      codec: "h264"
connections:
  - from: "unet_loader_high:0"
    to: "lora_loader_high:model"
  - from: "unet_loader_low:0"
    to: "lora_loader_low:model"
  - from: "lora_loader_high:0"
    to: "model_sampler_high:model"
  - from: "lora_loader_low:0"
    to: "model_sampler_low:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "camera_embed:0"
    to: "camera_preprocessor:camera_conditions"
  - from: "pos_prompt:0"
    to: "camera_preprocessor:positive"
  - from: "neg_prompt:0"
    to: "camera_preprocessor:negative"
  - from: "vae_loader:0"
    to: "camera_preprocessor:vae"
  - from: "start_image_loader:0"
    to: "camera_preprocessor:start_image"
  - from: "model_sampler_high:0"
    to: "ksampler_high:model"
  - from: "camera_preprocessor:0"
    to: "ksampler_high:positive"
  - from: "camera_preprocessor:1"
    to: "ksampler_high:negative"
  - from: "camera_preprocessor:2"
    to: "ksampler_high:latent_image"
  - from: "ksampler_high:0"
    to: "ksampler_low:latent_image"
  - from: "model_sampler_low:0"
    to: "ksampler_low:model"
  - from: "camera_preprocessor:0"
    to: "ksampler_low:positive"
  - from: "camera_preprocessor:1"
    to: "ksampler_low:negative"
  - from: "ksampler_low:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"
ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  start_image: "start_image_loader:image"
  aspect_ratio:
    width: ["camera_embed:width", "camera_preprocessor:width"]
    height: ["camera_embed:height", "camera_preprocessor:height"]
  video_length: ["camera_embed:length", "camera_preprocessor:length"]
  camera_pose: "camera_embed:camera_pose"
  speed: "camera_embed:speed"
  fx: "camera_embed:fx"
  fy: "camera_embed:fy"
  cx: "camera_embed:cx"
  cy: "camera_embed:cy"
  seed: "ksampler_high:noise_seed"
  filename_prefix: "save_video:filename_prefix"