nodes:
  unet_loader:
    class_type: UNETLoader
    title: "Load Diffusion Model"
    params:
      weight_dtype: "default"
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      type: "flux2"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "flux2-vae.safetensors"
  
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative)"
    
  latent_source:
    class_type: EmptyLatentImage
    title: "Empty Latent"

  ksampler:
    class_type: KSampler
    title: "KSampler"
    params:
      denoise: 1.0
      sampler_name: "euler"
      scheduler: "simple"

  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
    
  save_image:
    class_type: SaveImage
    title: "Save Image"

connections:
  - from: "unet_loader:0"
    to: "ksampler:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  
  - from: "pos_prompt:0"
    to: "ksampler:positive"
  - from: "neg_prompt:0"
    to: "ksampler:negative"
    
  - from: "latent_source:0"
    to: "ksampler:latent_image"
    
  - from: "ksampler:0"
    to: "vae_decode:samples"
  - from: "vae_decode:0"
    to: "save_image:images"

dynamic_lora_chains:
  lora_chain:
    template: "LoraLoader"
    output_map:
      "unet_loader:0": "model"
      "clip_loader:0": "clip"
    input_map:
      "model": "model"
      "clip": "clip"
    end_input_map:
      "model": ["ksampler:model"]
      "clip": ["pos_prompt:clip", "neg_prompt:clip"]

dynamic_reference_latent_chains:
  reference_latent_chain:
    ksampler_node: "ksampler"
    vae_node: "vae_loader"

ui_map:
  unet_name: "unet_loader:unet_name"
  clip_name: "clip_loader:clip_name"
  
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  
  width: "latent_source:width"
  height: "latent_source:height"
  batch_size: "latent_source:batch_size"
  
  seed: "ksampler:seed"
  steps: "ksampler:steps"
  cfg: "ksampler:cfg"
  
  filename_prefix: "save_image:filename_prefix"