nodes:
  unet_loader:
    class_type: UNETLoader
    title: "Load Diffusion Model"
    params:
      unet_name: "wan2.1_t2v_14b_scaled_fp8_e4m3_lightx2v_4step_comfyui.safetensors"
      weight_dtype: "default"
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      clip_name: "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
      type: "wan"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "wan_2.1_vae.safetensors"
  latent_video_gen:
    class_type: EmptyHunyuanLatentVideo
    title: "Empty Latent Video"
    params:
      batch_size: 1
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative Prompt)"
  model_sampler:
    class_type: ModelSamplingSD3
    title: "Model Sampler"
    params:
      shift: 8.0
  ksampler:
    class_type: KSampler
    title: "KSampler"
    params:
      steps: 4
      cfg: 1.0
      sampler_name: "uni_pc"
      scheduler: "simple"
      denoise: 1.0
  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
  create_video:
    class_type: CreateVideo
    params:
      fps: 16
  save_video:
    class_type: SaveVideo
    title: "Save Video"
    params:
      format: "auto"
      codec: "auto"

dynamic_lora_model_only_chains:
  loras_model_only:
    template: LoraLoaderModelOnly
    output_map:
      "unet_loader:0": model
    end_input_map:
      model: "model_sampler:model"

dynamic_easycache_chains:
  use_easy_cache:
    ksampler_node: "ksampler"

connections:
  - from: "unet_loader:0"
    to: "model_sampler:model"
  - from: "model_sampler:0"
    to: "ksampler:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "pos_prompt:0"
    to: "ksampler:positive"
  - from: "neg_prompt:0"
    to: "ksampler:negative"
  - from: "latent_video_gen:0"
    to: "ksampler:latent_image"
  - from: "ksampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"

ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  aspect_ratio:
    width: "latent_video_gen:width"
    height: "latent_video_gen:height"
  video_length: "latent_video_gen:length"
  seed: "ksampler:seed"
  filename_prefix: "save_video:filename_prefix"