nodes:
  t2v_unet:
    class_type: UNETLoader
    title: "Load 480p Diffusion Model"
    params:
      unet_name: "hunyuanvideo1.5_480p_t2v_cfg_distilled_fp8_scaled.safetensors"
      weight_dtype: "default"
  t2v_lora:
    class_type: LoraLoaderModelOnly
    title: "Load 480p Lightning LoRA"
    params:
      lora_name: "hunyuanvideo1.5_t2v_480p_lightx2v_4step_lora_rank_32_bf16.safetensors"
      strength_model: 1.0
  clip_loader:
    class_type: DualCLIPLoader
    title: "Load Dual CLIP"
    params:
      clip_name1: "qwen_2.5_vl_7b_fp8_scaled.safetensors"
      clip_name2: "byt5_small_glyphxl_fp16.safetensors"
      type: "hunyuan_video_15"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "hunyuanvideo15_vae_fp16.safetensors"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative)"
  empty_latent:
    class_type: EmptyHunyuanVideo15Latent
    title: "Empty Latent Video"
    params:
      batch_size: 1
  t2v_model_sampler:
    class_type: ModelSamplingSD3
    title: "Model Sampler (480p)"
    params:
      shift: 5.0
  t2v_scheduler:
    class_type: BasicScheduler
    title: "Scheduler (480p)"
    params:
      scheduler: "simple"
      steps: 4
      denoise: 1.0
  t2v_noise:
    class_type: RandomNoise
    title: "Random Noise (480p)"
  t2v_sampler_select:
    class_type: KSamplerSelect
    title: "Sampler Select (480p)"
    params:
      sampler_name: "euler"
  t2v_guider:
    class_type: CFGGuider
    title: "CFG Guider (480p)"
    params:
      cfg: 1.0
  t2v_sampler:
    class_type: SamplerCustomAdvanced
    title: "Advanced Sampler (480p)"
  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
  create_video:
    class_type: CreateVideo
    title: "Create Video"
    params:
      fps: 24
  save_video:
    class_type: SaveVideo
    title: "Save Video"
    params:
      format: "auto"
      codec: "h264"

connections:
  - from: "t2v_unet:0"
    to: "t2v_lora:model"
  - from: "t2v_lora:0"
    to: "t2v_model_sampler:model"
  - from: "t2v_lora:0"
    to: "t2v_scheduler:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "t2v_model_sampler:0"
    to: "t2v_guider:model"
  - from: "pos_prompt:0"
    to: "t2v_guider:positive"
  - from: "neg_prompt:0"
    to: "t2v_guider:negative"
  - from: "t2v_noise:0"
    to: "t2v_sampler:noise"
  - from: "t2v_guider:0"
    to: "t2v_sampler:guider"
  - from: "t2v_sampler_select:0"
    to: "t2v_sampler:sampler"
  - from: "t2v_scheduler:0"
    to: "t2v_sampler:sigmas"
  - from: "empty_latent:0"
    to: "t2v_sampler:latent_image"
  - from: "t2v_sampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"

ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  width: "empty_latent:width"
  height: "empty_latent:height"
  video_length: "empty_latent:length"
  seed: "t2v_noise:noise_seed"
  filename_prefix: "save_video:filename_prefix"