nodes:
  clip_loader:
    class_type: CLIPLoader
    title: "Load CLIP"
    params:
      type: "wan"
      device: "default"
      clip_name: "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
  vae_loader:
    class_type: VAELoader
    title: "Load VAE"
    params:
      vae_name: "wan_2.1_vae.safetensors"
  unet_loader_high:
    class_type: UNETLoader
    title: "Load UNET High Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_fun_control_high_noise_14B_fp8_scaled.safetensors"
  unet_loader_low:
    class_type: UNETLoader
    title: "Load UNET Low Noise"
    params:
      weight_dtype: "default"
      unet_name: "wan2.2_fun_control_low_noise_14B_fp8_scaled.safetensors"
  lora_loader_high:
    class_type: LoraLoaderModelOnly
    title: "Load LoRA High Noise"
    params:
      strength_model: 1.0
      lora_name: "wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors"
  lora_loader_low:
    class_type: LoraLoaderModelOnly
    title: "Load LoRA Low Noise"
    params:
      strength_model: 1.0
      lora_name: "wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors"
  ref_image_loader:
    class_type: LoadImage
    title: "Load Reference Image"
  control_video_loader:
    class_type: LoadVideo
    title: "Load Control Video"
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive Prompt)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative Prompt)"
  control_to_video_preprocessor:
    class_type: Wan22FunControlToVideo
    title: "Wan22FunControlToVideo"
    params:
      batch_size: 1
  get_video_frames:
    class_type: GetVideoComponents
    title: "Get Video Components"
  upscale_frames:
    class_type: ImageScale
    title: "Upscale Image"
    params:
      upscale_method: "nearest-exact"
      crop: "disabled"
  canny_processor:
    class_type: Canny
    title: "Canny"
    params:
      low_threshold: 0.1
      high_threshold: 0.6
  model_sampler_high:
    class_type: ModelSamplingSD3
    params: { shift: 8.0 }
  model_sampler_low:
    class_type: ModelSamplingSD3
    params: { shift: 8.0 }
  ksampler_high:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) High Noise"
    params:
      add_noise: "enable"
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 0
      end_at_step: 2
      return_with_leftover_noise: "enable"
  ksampler_low:
    class_type: KSamplerAdvanced
    title: "KSampler (Advanced) Low Noise"
    params:
      add_noise: "disable"
      noise_seed: 0
      steps: 4
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"
      start_at_step: 2
      end_at_step: 4
      return_with_leftover_noise: "disable"
  vae_decode:
    class_type: VAEDecode
  create_video:
    class_type: CreateVideo
    params: { fps: 16 }
  save_video:
    class_type: SaveVideo
    params:
      format: "mp4"
      codec: "h264"
connections:
  - from: "unet_loader_high:0"
    to: "lora_loader_high:model"
  - from: "unet_loader_low:0"
    to: "lora_loader_low:model"
  - from: "lora_loader_high:0"
    to: "model_sampler_high:model"
  - from: "lora_loader_low:0"
    to: "model_sampler_low:model"
  - from: "control_video_loader:0"
    to: "get_video_frames:video"
  - from: "get_video_frames:0"
    to: "upscale_frames:image"
  - from: "upscale_frames:0"
    to: "canny_processor:image"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"
  - from: "pos_prompt:0"
    to: "control_to_video_preprocessor:positive"
  - from: "neg_prompt:0"
    to: "control_to_video_preprocessor:negative"
  - from: "vae_loader:0"
    to: "control_to_video_preprocessor:vae"
  - from: "ref_image_loader:0"
    to: "control_to_video_preprocessor:ref_image"
  - from: "canny_processor:0"
    to: "control_to_video_preprocessor:control_video"
  - from: "model_sampler_high:0"
    to: "ksampler_high:model"
  - from: "control_to_video_preprocessor:0"
    to: "ksampler_high:positive"
  - from: "control_to_video_preprocessor:1"
    to: "ksampler_high:negative"
  - from: "control_to_video_preprocessor:2"
    to: "ksampler_high:latent_image"
  - from: "ksampler_high:0"
    to: "ksampler_low:latent_image"
  - from: "model_sampler_low:0"
    to: "ksampler_low:model"
  - from: "control_to_video_preprocessor:0"
    to: "ksampler_low:positive"
  - from: "control_to_video_preprocessor:1"
    to: "ksampler_low:negative"
  - from: "ksampler_low:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "create_video:images"
  - from: "create_video:0"
    to: "save_video:video"
ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  ref_image: "ref_image_loader:image"
  control_video: "control_video_loader:file"
  aspect_ratio:
    width: ["control_to_video_preprocessor:width", "upscale_frames:width"]
    height: ["control_to_video_preprocessor:height", "upscale_frames:height"]
  video_length: "control_to_video_preprocessor:length"
  seed: "ksampler_high:noise_seed"
  filename_prefix: "save_video:filename_prefix"