nodes:
  unet_loader:
    class_type: UNETLoader
    title: "Load FLUX UNET"
    params:
      unet_name: "flux1-dev-fp8-e4m3fn.safetensors"
      weight_dtype: "default"
  lora_loader:
    class_type: LoraLoaderModelOnly
    title: "Load USO LoRA"
    params:
      lora_name: "uso-flux1-dit-lora-v1.safetensors"
      strength_model: 1.0
  clip_loader:
    class_type: DualCLIPLoader
    title: "Load FLUX Dual CLIP"
    params:
      clip_name1: "clip_l.safetensors"
      clip_name2: "t5xxl_fp8_e4m3fn_scaled.safetensors"
      type: "flux"
      device: "default"
  vae_loader:
    class_type: VAELoader
    title: "Load FLUX VAE"
    params:
      vae_name: "ae.safetensors"
      
  pos_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Positive)"
  neg_prompt:
    class_type: CLIPTextEncode
    title: "CLIP Text Encode (Negative)"
    
  latent_source:
    class_type: EmptySD3LatentImage
    title: "Empty Latent (SD3)"
    
  ksampler:
    class_type: KSampler
    title: "KSampler"
    params:
      denoise: 1.0
      steps: 20
      cfg: 1.0
      sampler_name: "euler"
      scheduler: "simple"

  vae_decode:
    class_type: VAEDecode
    title: "VAE Decode"
  save_image:
    class_type: SaveImage
    title: "Save Image"
    params: {}

connections:
  - from: "unet_loader:0"
    to: "lora_loader:model"
  - from: "clip_loader:0"
    to: "pos_prompt:clip"
  - from: "clip_loader:0"
    to: "neg_prompt:clip"

  - from: "lora_loader:0"
    to: "ksampler:model"
  - from: "pos_prompt:0"
    to: "ksampler:positive"
  - from: "neg_prompt:0"
    to: "ksampler:negative"
  - from: "latent_source:0"
    to: "ksampler:latent_image"
  - from: "ksampler:0"
    to: "vae_decode:samples"
  - from: "vae_loader:0"
    to: "vae_decode:vae"
  - from: "vae_decode:0"
    to: "save_image:images"

dynamic_lora_chains:
  lora_chain:
    template: "LoraLoader"
    output_map:
      "unet_loader:0": "model"
      "clip_loader:0": "clip"
    input_map:
      "model": "model"
      "clip": "clip"
    end_input_map:
      "model": ["lora_loader:model"]
      "clip": ["pos_prompt:clip", "neg_prompt:clip"]

dynamic_USO_Reference_chains:
  uso_reference_chain:
    start: "pos_prompt"
    output_map:
      "0": "conditioning"
    end_input_map:
      "conditioning": ["ksampler:positive"]

dynamic_USO_StyleReference_chains:
  uso_style_reference_chain:
    start: "lora_loader"
    output_map:
      "0": "model"
    end_input_map:
      "model": ["ksampler:model"]

ui_map:
  positive_prompt: "pos_prompt:text"
  negative_prompt: "neg_prompt:text"
  width: "latent_source:width"
  height: "latent_source:height"
  batch_size: "latent_source:batch_size"
  seed: "ksampler:seed"
  filename_prefix: "save_image:filename_prefix"